#Seata Configuration:
seata:
  ##nacos config center
  config:
    type: nacos
    nacos:
      server-addr: localhost:8848
      namespace: 5b343571-c690-41f3-a45e-9e7b09f9d708
      group: shop
      data-id: seata.properties

  ##nacos service registry
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8848

  tx-service-group: zzx_seata_tx_group
  service:
    vgroup-mapping:
      zzx_seata_tx_group: default